version: '2'

networks:
  app-tier:
    driver: bridge

services:
  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
      # - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier






  jaeger:
    image: jaegertracing/all-in-one:1.50 # 使用较新版本
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "6831:6831/udp" # Jaeger Agent (Thrift)
      - "14268:14268" # Jaeger Collector (HTTP)
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    restart: always


